spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URI}
  data:
    elasticsearch:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://recruitment.cdyiuq4e8a2n.ap-northeast-2.rds.amazonaws.com:3306/recruitment?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: recruitment
    password: ${batchpw}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect